### PR TITLE
Add support for custom format

### PR DESCRIPTION
**Pull request by louisld**
I tried to implement custom format for zotero links as described in issue #13.

Tell me if it suits your project of if you want to change some behaviour.

### CODE REVIEW

**Comment by jannessm** [comment]
Hey, sorry that it took so long for me to give feedback. I haven't tested it yet, but thank you very much for your effort!

Could you please change the following: 
- Remove the Boolean flag and add a default value as the current template
- do not pass all the settings to zoteroItem. Just the ones it needs.

Again: thank you!

**Comment by jannessm** [comment]
Another suggestion: please add the opportunity to format the date using normal date formatting syntax, e.g.: <date:YYYY-MM-DDTHH:mm:ss.sssZ>

**Comment by louisld** [comment]
I did not have a lot of time lately but I have finally updated the code.

I added the `month` option with default `en-US` format since most paper are written in English as well as a `monthlocal` option to use the local format of the computer. What do you think of this ?

I will start to work on a custom date format using regex and date formatting.

**Comment by louisld** [comment]
I implemented the date formatting but it looks a bit tricky since I did not found js function to parse `YYYY-MM-DDTHH:mm:ss`.

Tell me if you think of a better implementation.

**Comment by jannessm** [comment]
Hey, Great work so far. Honestly, I thought there might be a js function to parse such strings and format a string accordingly.

Would you be so kind and use this lib: [dayjs](https://day.js.org/docs/en/display/format)

That would require to have a onchangelistener to validate if the given string is a valid format. Otherwise an alert should be given.

[Joplin API](https://joplinapp.org/api/references/plugin_api/classes/joplinsettings.html)

**Comment by louisld** [comment]
Now the date is parsed with dayjs.

I don't think the format can be not valid since there si no wrong format, only wrong date as explained here: https://day.js.org/docs/en/parse/is-valid.

**Pull request merged**
