### PR TITLE
[fix] URL for local zotero api

### PR DESCRIPTION
**Pull request by butterflyx**

### CODE REVIEW

**Comment by Korisis** [comment]
Did the JSON response from Zotero also change? I had to change line 134 and 135 to get it working:
`data = data.filter(item => item.data.itemType !== 'attachment' && item.data.itemType !== 'note').map(item => new ZoteroItem(item.data));`

**Comment by jannessm** [comment]
seems so. could you please add it to your PR? That would help me a lot! Thank you for your contribution!

**Comment by butterflyx** [comment]
done

**Comment by jannessm** [comment]
Thank you for your contribution!

**Pull request merged**
